name: CVChat
main: org.cubeville.cvchat.CVChat
authors: [FrediW,unixadmin]
version: 0.1
depend: [CVIPC,SuperVanish,WorldGuard]

commands:
  modreq:
    description: Send moderator request
  unlocktutorialchat:
    description: Unlocks tutorial chat
  ltr:
    description: Fake local chat
    permission: cvchat.fakelocal
  addlocalregion:
    description: Add local chat for region.
    permission: cvchat.local.regionchat
  removelocalregion:
    description: Remove a region-based local chat.
    permission: cvchat.local.regionchat
